webserver:
  port: 8060
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  port: 1407

catalog-service:
  host: localhost
  port: 1408

auth-service:
  host: localhost
  port: 7070

health:
  readiness:
    idle-timeout: 2000
