webserver:
  port: 10120
  host: "0.0.0.0"
  access-log:
    format: "%h %u %t %r %s %b %{Referer}i %T"

grpcserver:
  port: 10128

catalog-service:
  host: localhost
  port: 10118

auth-service:
  host: localhost
  port: 10108

health:
  readiness:
    idle-timeout: 2000
