@startuml
title Docker deployment diagram

cloud "Google Cloud storage" as storage
actor user
cloud "dapla-spark-service" as lds


frame zeppelin-dapla {
  component zeppelin
  component spark
  artifact [dapla-spark-plugin] as plugin
  artifact [gcs-connector-hadoop] as gcs
}

spark -(0- zeppelin
spark o-- plugin
spark o-- gcs
gcs -0)- storage
plugin -0)- "HTTP" lds

user -right- zeppelin : HTTP 8080
@enduml